---
version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=admin
      - POSTGRES_DB=test-db
    ports:
      - "5432:5432"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/create_tables.sql