spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-db
    username: admin
    password: pwd